import Black_Mamba_Boy from './Black Mamba Boy.jgp'
import Ce_que_murmurent_les_collines from './Ce_que_murmurent_les_collines.jpg'
import Chasing_the_Leopard_Finding_the_Lion from './Chasing_the_Leopard_Finding_the_Lion.jpg'
import Dance_of_the_Jakaranda from './Dance_of_the_Jakaranda.jpg'
import Desertion from './Desertion.jpeg'
import Dust from './Dust.jpg'
import Kintu from './Kintu.jpeg'
import LHomme_Qui_Répare_Les_Femmes from './LHomme_Qui_Répare_Les_Femmes.jpeg'
import Links from './Links.jpg'
import Miracle_in_Kigali from './Miracle_in_Kigali.webp'
import Our_Lady_of_the_Nile from './Our_Lady_of_the_Nile.jpg'
import Paradise from './Paradise.jpeg'
import Petals_of_Blood from './Petals_of_Blood.jpg'
import Rwanda_Means_the_Universe from './Rwanda_Means_the_Universe.jpg'
import secrets_no_more from './secrets_no_more.jpeg'
import small_country from './small_country.jpg'
import Song_for_Night from './Song_for_Night.webp'
import The_Barefoot_Woman from './The_Barefoot_Woman.jpg'
import The_Bell from './The_Bell.jpeg'
import The_Boy_Who_Tried_to_Silence_the_Sun from './The_Boy_Who_Tried_to_Silence_the_Sun.jpg'
import The_First_Woman from './The_First_Woman.jpg'
import The_Last_Gift from './The_Last_Gift.jpeg'
import The_River_Between from './The_River_Between.jpg'
import Unbowed from './Unbowed.jpeg'
import Waiting from './Waiting.jpg'
import Weep_Not_Child from './Weep_Not_Child.jpeg'
import Baho from './Baho.jpeg'
import The_Heart_of_Darkness from './The_Heart_of_Darkness.jpg'
import Black_Moses from './Black_Moses.jpg'
import Weep_Not_Refugee from './Weep_Not_ Refugee.jpg'

let product = [
    
]